name: Airflow DAG CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dag-ci-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run DAG import tests
        run: pytest tests/